pull_request_rules:
  - name: Automatic merge when CI passes + review approved
    description: Merge PR when all checks pass and approved (with hotfix override)
    conditions:
      - or:
          - label = hotfix
          - and:
              - "#approved-reviews-by >= 1"
              - "#changes-requested-by = 0"
              - "#comment-thread-created = 0"
      - check-success = CI
    actions:
      merge:
        method: squash

  - name: Make sure PRs are up to date before merging with rebase
    description: Automatically rebases PRs when they are out-of-date with the base branch
    conditions:
      - "#commits-behind >= 10"
    actions:
      rebase:

  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR has conflicts
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
