pull_request_rules:
  - name: Automatic merge when CI passes + review approved + office hours or hotfix
    description: Merge PR when all checks pass, approved, and during office hours or with hotfix label
    conditions:
      - or:
          - schedule = Mon-Fri 09:00-17:00[America/Los_Angeles]
          - label = hotfix
      - "#approved-reviews-by >= 1"
      - "#changes-requested-by = 0"
      - "#comment-thread-created = 0"
      - check-success = CI
    actions:
      merge:
        method: squash

  - name: Make sure PRs are up to date before merging with rebase
    description: Automatically rebases PRs when they are out-of-date with the base branch
    conditions:
      - "#commits-behind >= 10"
    actions:
      rebase:

  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR has conflicts
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
